### ISSUE TITLE
`tracks` path includes albums in place of artists

### ISSUE THREAD

**Issue by jade-doggerel** [tidal-music/tidal-sdk-web#164] opened 2024-07-28 08:15 UTC
Hey there - I dunno if I'm missing something here but I am not sure this is working as intended...
What'd I'm trying to do is to pass a track ID to the catalogue API and return the title and artist in the same call. Here's what I have been testing with:
```js
await catalogueClient.GET('/tracks/{id}', {
  params: {
    path: {id},
    query: {countryCode: 'NO', include: 'artists'},
  },
});
```
using ID `343267475`, the `data.relationships` object looks like this:

```json
"relationships": {
  "albums": {
    "links": {
      "self": "/tracks/330476412/relationships/albums?countryCode=NO"
    }
  },
  "artists": {
    "data": [
      {
        "id": "330476411",
        "type": "albums"
      }
    ],
    "links": {
      "self": "/tracks/330476412/relationships/albums?countryCode=NO"
    }
  },
  "providers": {
    "links": {
      "self": "/tracks/330476412/relationships/providers?countryCode=NO"
    }
  },
  "similarTracks": {
    "links": {
      "self": "/tracks/330476412/relationships/similarTracks?countryCode=NO"
    }
  }
}
```
note that `artists` has returned a relationship of type `albums`. The `included` object is also the album (full response is [here](https://gist.github.com/jade-doggerel/66add169d0b411ea7b1b72aeb120d20e)). If I don't pass the `include` param, it works fine:
```json
"relationships": {
  "albums": {
    "links": {
      "self": "/tracks/343267475/relationships/albums?countryCode=NO"
    }
  },
  "artists": {
    "links": {
      "self": "/tracks/343267475/relationships/artists?countryCode=NO"
    }
  },
  "providers": {
    "links": {
      "self": "/tracks/343267475/relationships/providers?countryCode=NO"
    }
  },
  "similarTracks": {
    "links": {
      "self": "/tracks/343267475/relationships/similarTracks?countryCode=NO"
    }
  }
}
```
but I'd then need to make an additional call to fetch the artist details. 
The `component` seems correct:
https://github.com/tidal-music/tidal-sdk-web/blob/9ee48fc0c42bc02143920d0ef9ddb5f75734fc9f/packages/catalogue/src/catalogueAPI.d.ts#L554
so I'm guessing this is an upstream problem?

As an aside, probably not related as it pertains to `similarAlbums` but I also spotted some oddities in `paths`:

https://github.com/tidal-music/tidal-sdk-web/blob/9ee48fc0c42bc02143920d0ef9ddb5f75734fc9f/packages/catalogue/src/catalogueAPI.d.ts#L58-L64

which points to:

https://github.com/tidal-music/tidal-sdk-web/blob/9ee48fc0c42bc02143920d0ef9ddb5f75734fc9f/packages/catalogue/src/catalogueAPI.d.ts#L2433-L2460

which means the `similarAlbums` path gets a `_1`:

https://github.com/tidal-music/tidal-sdk-web/blob/9ee48fc0c42bc02143920d0ef9ddb5f75734fc9f/packages/catalogue/src/catalogueAPI.d.ts#L156-L162

Lemme know if I can provide anything 👍

**Comment by jade-doggerel** [comment] 2024-08-03 09:29
Just a quick follow up - forgot to mention that shortly after I posted this, I tested with a regular non-SDK HTTP request and the results are the same (see below).
Seeing as this is likely an upstream issue, is there a better place for me to post it?

![image](https://github.com/user-attachments/assets/1cb2e037-a516-490d-b52c-67b8f1099c7f)

**Comment by osmestad** [comment] 2024-08-06 11:16
Yes this definitely looks like a bug at our API level! 
@aliaksei-taliuk can you take a look? (I can reproduce the problem here when using track id `343267475` and including `artists`)
Thanks for reporting!

(As for the issue with `similarAlbums`, we have fixed that in the OpenAPI definition, but still need to publish a new version of the SDK, will try to get that out shortly :-) )

**Comment by aliaksei-taliuk** [comment] 2024-08-06 19:41
@jade-doggerel The fix has been deployed. Thanks for reporting it!

**Comment by osmestad** [comment] 2024-08-07 10:53
And the SDK has also been published with a fix for the `similarTracks` / `similarAlbums` now :-)

**Closed by osmestad** 2024-08-07 10:53 UTC
